language: python
python: '3.6'
cache: pip
before_install:
- openssl aes-256-cbc -K $encrypted_721a23b33185_key -iv $encrypted_721a23b33185_iv
  -in keyfile.enc -out keyfile -d
install:
- pip install -r requirements.txt
- sudo bash install_gitcrypt.sh
script:
  - git-crypt unlock keyfile
  - python manage.py test

deploy:
  provider: script
  script: "./zappa_deploy.sh"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^develop|master|travis-test$