language: python
python: '3.6'

before_install:
  - openssl aes-256-cbc -K $encrypted_721a23b33185_key -iv $encrypted_721a23b33185_iv -in keyfile.enc -out keyfile -d
  - bash crypt.sh
  - git-crypt unlock keyfile
install:
  - pip install -r requirements.txt

stages:
  - name: test
  - name: develop
    if: branch = develop
  - name: production
    if: branch = master

jobs:
  include:
    - stage: test
      script: echo "TODO tests"
    - stage: develop
      script:
      - echo "TODO test"
      - zappa update dev
    - stage: production
      script:
        - echo "TODO test"
        - zappa update prod


