language: python
python: '3.6'
install:
  - pip install -r requirements.txt

stages:
  - name: test
  - name: develop
    if: branch = develop
  - name: production
    if: branch = master

jobs:
  include:
    - stage: test
      script: echo "TODO tests"
    - stage: develop
      script:
      - echo "TODO test"
      - zappa update dev
    - stage: production
      script:
        - echo "TODO test"
        - zappa update prod


