language: python
python: '3.6'
cache: pip
before_install:
- openssl aes-256-cbc -K $encrypted_721a23b33185_key -iv $encrypted_721a23b33185_iv
  -in keyfile.enc -out keyfile -d
install:
- pip install -r requirements.txt
- sudo bash install_gitcrypt.sh
stages:
- name: test
- name: develop
- name: production

jobs:
  include:
  - stage: test
    script: echo "TODO tests"

  - stage: develop
    if: branch = develop
    name: "Deploy to api-dev"
    script:
    - echo "TODO test" && git-crypt unlock keyfile
    deploy:
      provider: script
      script: zappa update dev
      on:
        branch: develop

  - stage: production
    if: branch = master
    name: "Deploy to apiv1"
    script:
    - echo "TODO test" && git-crypt unlock keyfile
    deploy:
      provider: script
      script: zappa update prod
      on:
        branch: master
