# Generated by Django 2.2.1 on 2019-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translation_type',
            field=models.CharField(choices=[('transliteration', 'Transliteration')], default='transliteration', max_length=32),
        ),
    ]
