# Generated by Django 2.2.1 on 2019-05-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_translation_translation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayahword',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surah',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
